(include-book "../file-system-m2")

(slurp-disk-image
 fat32-in-memory "/tmp/disk1.raw"  state)

(pprogn
 (princ$ "mkfs.fat 3.0.28 (2015-05-16)" *standard-co* state)
 (newline *standard-co* state)
 (princ$ "/tmp/disk1.raw has " *standard-co* state)
 (princ$ (bpb_numheads fat32-in-memory) *standard-co* state)
 (princ$ " heads and " *standard-co* state)
 (princ$ (bpb_secpertrk fat32-in-memory) *standard-co* state)
 (princ$ " sectors per track," *standard-co* state)
 (newline *standard-co* state)
 (princ$ "hidden sectors 0x" *standard-co* state)
 (set-print-base 16 state)
 (princ$ (bpb_hiddsec fat32-in-memory) *standard-co* state)
 (set-print-base 10 state)
 (princ$ ";" *standard-co* state)
 (newline *standard-co* state)
 (princ$ "logical sector size is " *standard-co* state)
 (princ$ (bpb_bytspersec fat32-in-memory) *standard-co* state)
 (princ$ ";" *standard-co* state)
 (newline *standard-co* state)
 (princ$ "using 0x" *standard-co* state)
 (set-print-base 16 state)
 (princ$ (bpb_media fat32-in-memory) *standard-co* state)
 (set-print-base 10 state)
 (princ$ " media descriptor, with " *standard-co* state)
 (princ$ (bpb_totsec32 fat32-in-memory) *standard-co* state)
 (princ$ " sectors;" *standard-co* state)
 (newline *standard-co* state)
 (princ$ "drive number 0x" *standard-co* state)
 (set-print-base 16 state)
 (princ$ (bs_drvnum fat32-in-memory) *standard-co* state)
 (set-print-base 10 state)
 (princ$ ";" *standard-co* state)
 (newline *standard-co* state)
 (princ$ "filesystem has " *standard-co* state)
 (princ$ (bpb_numfats fat32-in-memory) *standard-co* state)
 (princ$ " 32-bit FATs and " *standard-co* state)
 (princ$ (bpb_secperclus fat32-in-memory) *standard-co* state)
 (princ$ " sectors per cluster." *standard-co* state)
 (newline *standard-co* state)
 (princ$ "FAT size is " *standard-co* state)
 (princ$ (bpb_fatsz32 fat32-in-memory) *standard-co* state)
 (princ$ " sectors, and provides " *standard-co* state)
 (princ$ (/ (- (bpb_totsec32 fat32-in-memory)
               (+ (bpb_rsvdseccnt fat32-in-memory)
                  (* (bpb_numfats fat32-in-memory)
                     (bpb_fatsz32 fat32-in-memory))))
            (bpb_secperclus fat32-in-memory))
         *standard-co*
         state)
 (princ$ " clusters." *standard-co* state)
 (newline *standard-co* state)
 (princ$ "There are " *standard-co* state)
 (princ$ (bpb_rsvdseccnt fat32-in-memory) *standard-co* state)
 (princ$ " reserved sectors." *standard-co* state)
 (newline *standard-co* state)
 (princ$ "Volume ID is " *standard-co* state)
 (set-print-base 16 state)
 (princ$ (bs_volid fat32-in-memory) *standard-co* state)
 (set-print-base 10 state)
 (princ$ ", no volume label." *standard-co* state)
 (newline *standard-co* state))
