(include-book "../file-system-m2")

(slurp-disk-image
 fat32-in-memory "/tmp/disk1.raw"  state)

(mv-let
  (channel state)
  (open-output-channel "output.txt" :character state)
  (pprogn
   (princ$ "mkfs.fat 3.0.28 (2015-05-16)" channel state)
   (newline channel state)
   (princ$ "/tmp/disk1.raw has " channel state)
   (princ$ (bpb_numheads fat32-in-memory) channel state)
   (princ$ " heads and " channel state)
   (princ$ (bpb_secpertrk fat32-in-memory) channel state)
   (princ$ " sectors per track," channel state)
   (newline channel state)
   (princ$ "hidden sectors 0x" channel state)
   (set-print-base 16 state)
   (princ$ (bpb_hiddsec fat32-in-memory) channel state)
   (set-print-base 10 state)
   (princ$ ";" channel state)
   (newline channel state)
   (princ$ "logical sector size is " channel state)
   (princ$ (bpb_bytspersec fat32-in-memory) channel state)
   (princ$ ";" channel state)
   (newline channel state)
   (princ$ "using 0x" channel state)
   (set-print-base 16 state)
   (princ$ (bpb_media fat32-in-memory) channel state)
   (set-print-base 10 state)
   (princ$ " media descriptor, with " channel state)
   (princ$ (bpb_totsec32 fat32-in-memory) channel state)
   (princ$ " sectors;" channel state)
   (newline channel state)
   (princ$ "drive number 0x" channel state)
   (set-print-base 16 state)
   (princ$ (bs_drvnum fat32-in-memory) channel state)
   (set-print-base 10 state)
   (princ$ ";" channel state)
   (newline channel state)
   (princ$ "filesystem has " channel state)
   (princ$ (bpb_numfats fat32-in-memory) channel state)
   (princ$ " 32-bit FATs and " channel state)
   (princ$ (bpb_secperclus fat32-in-memory) channel state)
   (princ$ " sectors per cluster." channel state)
   (newline channel state)
   (princ$ "FAT size is " channel state)
   (princ$ (bpb_fatsz32 fat32-in-memory) channel state)
   (princ$ " sectors, and provides " channel state)
   (princ$ (/ (- (bpb_totsec32 fat32-in-memory)
                 (+ (bpb_rsvdseccnt fat32-in-memory)
                    (* (bpb_numfats fat32-in-memory)
                       (bpb_fatsz32 fat32-in-memory))))
              (bpb_secperclus fat32-in-memory))
           channel
           state)
   (princ$ " clusters." channel state)
   (newline channel state)
   (princ$ "There are " channel state)
   (princ$ (bpb_rsvdseccnt fat32-in-memory) channel state)
   (princ$ " reserved sectors." channel state)
   (newline channel state)
   (princ$ "Volume ID is " channel state)
   (set-print-base 16 state)
   (princ$ (bs_volid fat32-in-memory) channel state)
   (set-print-base 10 state)
   (princ$ ", no volume label." channel state)
   (newline channel state)
   (close-output-channel channel state)))
